function createfigure(ts1, getcolumn1, getcolumn2, getcolumn3, ts2, getcolumn4, getcolumn5, getcolumn6, getcolumn7, getcolumn8, getcolumn9)
%CREATEFIGURE(ts1, getcolumn1, getcolumn2, getcolumn3, ts2, getcolumn4, getcolumn5, getcolumn6, getcolumn7, getcolumn8, getcolumn9)
%  TS1:  vector of stairs x data
%  GETCOLUMN1:  vector of stairs y data
%  GETCOLUMN2:  vector of stairs y data
%  GETCOLUMN3:  vector of stairs y data
%  TS2:  vector of stairs x data
%  GETCOLUMN4:  vector of stairs y data
%  GETCOLUMN5:  vector of stairs y data
%  GETCOLUMN6:  vector of stairs y data
%  GETCOLUMN7:  vector of stairs y data
%  GETCOLUMN8:  vector of stairs y data
%  GETCOLUMN9:  vector of stairs y data

%  Auto-generated by MATLAB on 07-May-2025 22:53:52

% Create figure
figure1 = figure('WindowState','maximized');

% Create subplot
subplot1 = subplot(3,3,1,'Parent',figure1);
hold(subplot1,'on');

% Create stairs
stairs(ts1,getcolumn1,'DisplayName','OBSERVATION/local_acc:1.local_y',...
    'Parent',subplot1,...
    'LineWidth',2,...
    'Color',[0 0.447 0.741]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-0.7492431640625 0.6735595703125]);
box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Location','northoutside','Interpreter','none');

% Create subplot
subplot2 = subplot(3,3,2,'Parent',figure1);
hold(subplot2,'on');

% Create stairs
stairs(ts1,getcolumn2,'DisplayName','OBSERVATION/local_acc:1.local_x',...
    'Parent',subplot2,...
    'LineWidth',2,...
    'Color',[0.133 0.71 0.451]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-0.507666015625 0.697607421875]);
box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Location','northoutside','Interpreter','none');

% Create subplot
subplot3 = subplot(3,3,3,'Parent',figure1);
hold(subplot3,'on');

% Create stairs
stairs(ts1,getcolumn3,'DisplayName','OBSERVATION/local_acc:1.local_z',...
    'Parent',subplot3,...
    'LineWidth',2,...
    'Color',[0.85 0.325 0.098]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-0.08463134765625 1.77725830078125]);
box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend3 = legend(subplot3,'show');
set(legend3,'Location','northoutside','Interpreter','none');

% Create subplot
subplot4 = subplot(3,3,4,'Parent',figure1);
hold(subplot4,'on');

% Create stairs
stairs(ts2,getcolumn4,'DisplayName','OBSERVATION/acc_calibrated:1.Y',...
    'Parent',subplot4,...
    'LineWidth',2,...
    'Color',[0.929 0.694 0.125]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[-0.905279541015625 0.468511962890625]);
box(subplot4,'on');
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend4 = legend(subplot4,'show');
set(legend4,'Location','northoutside','Interpreter','none');

% Create subplot
subplot5 = subplot(3,3,5,'Parent',figure1);
hold(subplot5,'on');

% Create stairs
stairs(ts2,getcolumn5,'DisplayName','OBSERVATION/acc_calibrated:1.X',...
    'Parent',subplot5,...
    'LineWidth',2,...
    'Color',[0.85 0.325 0.098]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot5,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot5,[-0.524819946289062 0.346170043945312]);
box(subplot5,'on');
hold(subplot5,'off');
% Set the remaining axes properties
set(subplot5,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend5 = legend(subplot5,'show');
set(legend5,'Location','northoutside','Interpreter','none');

% Create subplot
subplot6 = subplot(3,3,6,'Parent',figure1);
hold(subplot6,'on');

% Create stairs
stairs(ts2,getcolumn6,'DisplayName','OBSERVATION/acc_calibrated:1.Z',...
    'Parent',subplot6,...
    'LineWidth',2,...
    'Color',[0.494 0.184 0.556]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot6,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot6,[-0.747665405273438 0.535690307617188]);
box(subplot6,'on');
hold(subplot6,'off');
% Set the remaining axes properties
set(subplot6,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend6 = legend(subplot6,'show');
set(legend6,'Location','northoutside','Interpreter','none');

% Create subplot
subplot7 = subplot(3,3,7,'Parent',figure1);
hold(subplot7,'on');

% Create stairs
stairs(ts2,getcolumn7,'DisplayName','OBSERVATION/delta:1.Y',...
    'Parent',subplot7,...
    'LineWidth',2,...
    'Color',[0.392 0.831 0.075]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot7,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot7,[-0.37 1.17]);
box(subplot7,'on');
hold(subplot7,'off');
% Set the remaining axes properties
set(subplot7,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend7 = legend(subplot7,'show');
set(legend7,'Location','northoutside','Interpreter','none');

% Create subplot
subplot8 = subplot(3,3,8,'Parent',figure1);
hold(subplot8,'on');

% Create stairs
stairs(ts2,getcolumn8,'DisplayName','OBSERVATION/delta:1.X',...
    'Parent',subplot8,...
    'LineWidth',2,...
    'Color',[0.718 0.275 1]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot8,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot8,[-0.55 0.55]);
box(subplot8,'on');
hold(subplot8,'off');
% Set the remaining axes properties
set(subplot8,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend8 = legend(subplot8,'show');
set(legend8,'Location','northoutside','Interpreter','none');

% Create subplot
subplot9 = subplot(3,3,9,'Parent',figure1);
hold(subplot9,'on');

% Create stairs
stairs(ts2,getcolumn9,'DisplayName','OBSERVATION/delta:1.Z',...
    'Parent',subplot9,...
    'LineWidth',2,...
    'Color',[1 0.075 0.651]);

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot9,[505.840348848938 522.495713099681]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot9,[-0.89 1.09]);
box(subplot9,'on');
hold(subplot9,'off');
% Set the remaining axes properties
set(subplot9,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend9 = legend(subplot9,'show');
set(legend9,'Location','northoutside','Interpreter','none');

